<a href="https://colab.research.google.com/github/sokrypton/ColabBio/blob/main/rmsd_compute.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import jax.numpy as jnp
import numpy as np
import jax

In [ ]:
def jnp_kabsch(a, b):
  u, s, vh = jnp.linalg.svd(a.T @ b, full_matrices=False)
  u = jnp.where(jnp.linalg.det(u @ vh) < 0, u.at[:,-1].set(-u[:,-1]), u)
  return u @ vh

def jnp_rmsd(true, pred):
  p = true - true.mean(0,keepdims=True)
  q = pred - pred.mean(0,keepdims=True)
  p = p @ jnp_kabsch(p, q)
  return jnp.sqrt(jnp.square(p-q).sum(-1).mean())

In [ ]:
jnp_rmsd_parallel = jax.jit(jax.vmap(jnp_rmsd,(None,0)))

In [ ]:
data = jnp.zeros((10000,43,3))

In [ ]:
%%time
results = []
for n in range(100):
  results.append(np.array(jnp_rmsd_parallel(data[n],data)))

CPU times: user 895 ms, sys: 64.8 ms, total: 960 ms
Wall time: 777 ms


In [ ]:
results

[array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0.,